name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - name: Cache node_modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install package dependencies
      run: npm ci

    - uses: MeilCli/npm-update-check-action@v4
      id: outdated

    - name: Update caniuse-db
      if:  ${{ contains(steps.outdated.outputs.npm_update_text, 'caniuse-db') }}
      run: npm install caniuse-db@1

    - name: Get meta-data
      id: set_var
      run: |
        content=`npm ls --json caniuse-db`
        
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        
        echo "::set-output name=metaData::$content"

    - uses: EndBug/add-and-commit@v7
      with:
        add: 'package.json package-lock.json --force'
        message: "Update `caniuse-db` to v${{ fromJson(steps.set_var.outputs.metaData).dependencies['caniuse-db'].version }}"

    - name: Version bump
      uses: reedyuk/npm-version@1.1.1
      with:
        version: ${{ fromJson(steps.set_var.outputs.metaData).dependencies['caniuse-db'].version }}

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}